docs_dir: docs
pages:
- [index.md, 'Documentation', 'Getting started']
- [installation.md, 'Documentation', 'Installation']
- [usage.md, 'Documentation', 'Using MFAStack']
- [scaling.md, 'Documentation', 'Scaling']
- [features.md, 'Documentation', 'Features']
- [possible_usage.md, 'Documentation', 'Integration candidates']
- [security.md, 'Documentation', 'Security consideration']
- [roadmap.md, 'Documentation', 'Roadmap']
- [api/REST.md, 'API', 'REST API']
- [api/CLI.md, 'API', 'CLI API']
- [sso/about.md, 'SSO', 'About']
- [sso/idp_module.md, 'SSO', 'IDP module']
- [sso/identity_manager.md, 'SSO', 'Identity manager']
- [licenses/mfalib.md, 'Licenses', 'MFALib Licence']
- [licenses/mfaserver.md, 'Licenses', 'MFA Stack Licence']

theme: readthedocs

site_name: MFA Stack
