docs_dir: docs
pages:
- [index.md, 'Getting started', 'Introduction']
- [installation.md, 'Getting started', 'Installation']
- [api.md, 'API', 'API Documentation']
- [cli.md, 'CLI', 'CLI Documentation']
- [integration-examples.md, 'Integration', 'Integration Examples']
- [integration-laravel.md, 'Integration', 'Laravel']
- [clustering.md, 'Guidelines', 'Clustering']
- [security-guidelines.md, 'Guidelines', 'Security']

site_name: MFA Stack
